BackendCST/Pages/Error.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.Extensions.Logging;
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;

namespace BackEndCST.Pages
{
    [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
    [IgnoreAntiforgeryToken]
    public class ErrorModel : PageModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);

        private readonly ILogger<ErrorModel> _logger;

        public ErrorModel(ILogger<ErrorModel> logger)
        {
            _logger = logger;
        }

        public void OnGet()
        {
            RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier;
        }
    }
}

BackendCST/Pages/Index.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.Extensions.Logging;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace BackEndCST.Pages
{
    public class IndexModel : PageModel
    {
        private readonly ILogger<IndexModel> _logger;

        public IndexModel(ILogger<IndexModel> logger)
        {
            _logger = logger;
        }

        public void OnGet()
        {

        }
    }
}

BackendCST/Pages/Inregistrare.cshtml.cs
using BackEndCST.VizualizareModele;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using System.Threading.Tasks;


namespace BackEndCST.Pages
{
    public class InregistrareModel : PageModel
    {
        private readonly UserManager<IdentityUser> utilizatori;
        private readonly SignInManager<IdentityUser> utilizatori_logare;
        

        [BindProperty]
        public Inregistrare ModelInreg { get; set; }
        public InregistrareModel(UserManager<IdentityUser> utilizatori, SignInManager<IdentityUser> utilizatori_logare)
        {
            this.utilizatori = utilizatori;
            this.utilizatori_logare = utilizatori_logare;
        }
       
        public void OnGet()
        {
        }

        public async Task<IActionResult> OnPostAsync()
        {
            if (ModelState.IsValid)
            {
                var user = new IdentityUser()
                {
                    UserName = ModelInreg.email,
                    Email = ModelInreg.email
                };

                var rezultat_inreg = await utilizatori.CreateAsync(user, ModelInreg.password);

                if (rezultat_inreg.Succeeded)
                {
                    await utilizatori_logare.SignInAsync(user, false);
                    return RedirectToPage("Index");
                }

                foreach(var eroare in rezultat_inreg.Errors)
                {
                    ModelState.AddModelError("", eroare.Description);
                    //in cazul unei erori se va apela clasa IdentityErrorDescriber
                }

            }
            return Page();
        }
    }
}

BackendCST/Pages/Login.cshtml.cs
using BackEndCST.VizualizareModele;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using System.Threading.Tasks;

namespace BackEndCST.Pages
{
    public class LoginModel : PageModel
    {

        private readonly SignInManager<IdentityUser> signIn;
        [BindProperty]
        public Login ModelLogin { get; set; }

        public LoginModel(SignInManager<IdentityUser> signIn)
        {
            this.signIn = signIn;
        }
        public void OnGet()
        {
        }

        public async Task<IActionResult> OnPostAsync(string URL_intoarcere = null)
        {
            if (ModelState.IsValid)
            {
                var rez = await signIn.PasswordSignInAsync(ModelLogin.Email, ModelLogin.Password, ModelLogin.tine_minte, false);
                if (rez.Succeeded)
                {
                    if(URL_intoarcere == null || URL_intoarcere == "/")
                    {
                        return RedirectToPage("Index");
                    }
                    else
                    {
                        return RedirectToPage(URL_intoarcere);
                    }
                }
                ModelState.AddModelError("", "Username-ul sau parola au fost introduse gresit");
            }
            return Page();
        }
    }
}

BackendCST/Pages/Logout.cshtml.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using System.Threading.Tasks;

namespace BackEndCST.Pages
{   [Authorize]
    public class LogoutModel : PageModel
    {
        private readonly SignInManager<IdentityUser> signInManager;

        public LogoutModel(SignInManager <IdentityUser> signInManager)
        {
            this.signInManager = signInManager;
        }
        public void OnGet()
        {
        }

        public async Task<IActionResult> OnPostLogoutAsync()
        {
            await signInManager.SignOutAsync();
            return RedirectToPage("Login");
        }

        public IActionResult OnPostNoLogoutAsync()
        {
            return RedirectToPage("Index");
        }
    }
}

BackendCST/Pages/Privacy.cshtml.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.Extensions.Logging;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace BackEndCST.Pages
{   
    [Authorize]
    public class PrivacyModel : PageModel
    {
        private readonly ILogger<PrivacyModel> _logger;

        public PrivacyModel(ILogger<PrivacyModel> logger)
        {
            _logger = logger;
        }

        public void OnGet()
        {
        }
    }
}

BackendCST/Pages/Index.cshtml
@page
@model IndexModel
@{
    ViewData["Title"] = "Home page";
}

<div class="text-center">
    <h1 class="display-4">Bine ai venit!</h1>
    <p>Au lucrat la site:Zibileanu Sabin si Budeanu Andreea</p>
</div>

BackendCST/Pages/Inregistrare.cshtml
@page
@model BackEndCST.Pages.InregistrareModel
@{
}


<link rel = "stylesheet" href = ""></link>
<div class = "container mt-5">
    <div class = "row justify-content-center align-items-center">
        <div class = "col-sm-12 col-md-12 col-lg-4"> 
            <h1 class="mb-3">Inregistrare</h1>

            <form method = "post">
                <div asp-validation-summary="All" class="text-danger">
                </div>
                <div class = "mb-3">
                    <label class = "form-label" asp-for = "ModelInreg.email">Adresa Mail:</label>
                    <input type="text" asp-for = "ModelInreg.email" class = "form-control"/>
                    <span asp-validation-for = "ModelInreg.email" class="text-danger"></span>
                </div>

                <div class = "mb-3">
                    <label class = "form-label" asp-for = "ModelInreg.password">Parola:</label>
                    <input type="password" asp-for = "ModelInreg.password" class = "form-control"/>
                    <span asp-validation-for = "ModelInreg.password" class="text-danger"></span>
                </div>

                <div class = "mb-3">
                    <label class = "form-label" asp-for = "ModelInreg.confirm_password">Confirma parola:</label>
                    <input type="password" asp-for = "ModelInreg.confirm_password" class = "form-control"/>
                    <span asp-validation-for = "ModelInreg.confirm_password" class="text-danger"></span>
                </div>

                <div class = "mb-3">
                    <button type = "submit" class = "btn btn-primary">Inregistreaza-te</button>

                </div>

            </form>
        </div>
    </div>
</div>

BackendCST/Pages/Login.cshtml
@page
@model BackEndCST.Pages.LoginModel
@{
}

<div class = "container mt-5">
    <div class = "row justify-content-center align-items-center">
        <div class = "col-sm-12 col-md-12 col-lg-4">
            <h1 class = "mb-3">Login</h1>
        <form method="post">
            <div class = "mb-3">
                <label class = "form-label" asp-for = "ModelLogin.Email">Email</label>
                <input type = "text" asp-for = "ModelLogin.Email" class = "form-control" />
                <span asp-validation-for = "ModelLogin.Email" class = "text-danger"></span>
            </div>
            <div class = "mb-3">
                <label class = "form-label" asp-for = "ModelLogin.Password">Parola</label>
                <input type = "password" asp-for = "ModelLogin.Password" class = "form-control" />
                <span asp-validation-for = "ModelLogin.Password" class = "text-danger"></span>
            </div>

             <div class = "mb-3 form-check">
                <input type = "checkbox" asp-for = "ModelLogin.tine_minte" class = "form-check-input" />
                <label class = "form-check-label" asp-for = "ModelLogin.tine_minte">Remember Me</label>
            </div>

            <div class = "mb-3"></div>
                <button type = "submit" class = "btn btn-primary">Login</button>
        </form>
        </div>
    </div>
</div>

BackendCST/Pages/Logout.cshtml
@page
@model BackEndCST.Pages.LogoutModel
@{
}

<form method = "post">
    <div class = "container mt-5">
        <div class = "row justify-content-center">
            <div class = "col-sm-12 col-md-12 col-lg-4">
                <p>Urmeaza sa iesi de pe site.Apasa da daca vrei sa iesi sau nu daca vrei sa mai ramai
                    <button class = "btn btn-primary" asp-page-handler="Logout">Da</button>
                    <button class = "btn btn-light ml-5 border-dark" asp-page-handler="NoLogout">Nu</button>
                </p>
            </div>
        </div>

    </div>
</form>